-- AlterTable
ALTER TABLE "PaymentAttempt"
ADD COLUMN "fraudStatus" TEXT NOT NULL DEFAULT '',
ADD COLUMN "paymentType" TEXT NOT NULL DEFAULT '',
ADD COLUMN "transactionTime" TIMESTAMP(3),
ADD COLUMN "settlementTime" TIMESTAMP(3),
ADD COLUMN "providerPayload" JSONB;

-- AlterTable
ALTER TABLE "Order"
ADD COLUMN "paymentReference" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customerCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customerName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customerEmail" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customerPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "salesChannelCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN "salesChannelName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "recipientName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "recipientPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "originDistrict" TEXT NOT NULL DEFAULT '',
ADD COLUMN "destinationDistrict" TEXT NOT NULL DEFAULT '',
ADD COLUMN "courier" TEXT NOT NULL DEFAULT '',
ADD COLUMN "courierService" TEXT NOT NULL DEFAULT '',
ADD COLUMN "shippingDescription" TEXT NOT NULL DEFAULT '',
ADD COLUMN "estimatedDelivery" TEXT NOT NULL DEFAULT '',
ADD COLUMN "provinceId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "provinceName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "cityId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "cityName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "districtId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "districtName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "postalCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN "streetAddress" TEXT NOT NULL DEFAULT '';
